name = "BasicNT"
uuid = "19e8fb6a-f911-474c-af47-316326d4397e"
authors = ["Jason M Graham"]
version = "0.1.0"

[deps]
Primes = "27ebfcd6-29c5-5fa9-bf4b-fb8fc14df3ae"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
